import Head from 'next/head';
import { useEffect, useState } from 'react';
import AddItemForm from '../components/addItemForm';
import { Button } from '../components/buttonStyles';
import ShowEditItem from '../components/item';
import { styled } from '../stitchesConfig';

export type Item = {
  id: number;
  title: string;
  details: string;
  isDone: number;
  foto: string;
  created_at: string;
  updated_at: string;
};

const ItemsContainer = styled('main', {
  display: 'grid',
  maxWidth: '960px',
  gridTemplateColumns: '1fr 1fr 3fr 6fr',
  gridGap: '1rem',
  padding: '1rem',
  margin: '0 auto',
  marginTop: '4rem',
});

export default function Home() {
  const [items, setItems] = useState<Item[] | null>(null);
  const [showAdd, setShowAdd] = useState(false);
  useEffect(() => {
    fetch('http://localhost/api/items')
      .then((response) => response.json())
      .then((items) => setItems(items));
  }, []);
  return (
    <div>
      <Head>
        <title>BeepRoger App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ItemsContainer>
        {items
          ? items.map((item) => (
              <ShowEditItem
                key={item.id}
                item={item}
                items={items}
                setItems={setItems}
              />
            ))
          : null}
      </ItemsContainer>
      {showAdd ? (
        <AddItemForm
          items={items!}
          setItems={setItems}
          setShowAdd={setShowAdd}
        />
      ) : null}
      {showAdd ? null : (
        <Button
          variant="green"
          css={{ marginLeft: '1rem', marginTop: '1rem' }}
          onClick={() => setShowAdd(true)}
        >
          Add an item
        </Button>
      )}
    </div>
  );
}
